---
# run this script as: `sudo ansible-playbook jetstream-playbook.yaml`
# run this first: `sudo ansible-galaxy install cmprescott.chrome`


- hosts: localhost
  roles:
     - { role: cmprescott.chrome, become: yes }
  tasks:
    # Check if user permissions for passwordless sudo are set up correctly:
    - lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    - lineinfile:
        path: /etc/sudoers.d/90-cloudimg-ubuntu
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    # Remove line (usually at end of file) that would negate passwordless sudo access for all admins
    - lineinfile:
        path: /etc/sudoers
        regexp: '^%users ALL=(ALL) ALL'
        state: absent

    # TO DO: Automatically delete any occurrences of `%users ALL=(ALL) ALL` that occur in /etc/sudoers (use lineinfile for this?)

    # Set up users and groups:
    - user:
        name: jhaber
        uid: 1000
        comment: "Jaren Haber"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: aculich
        uid: 1001
        comment: "Aaron Culich"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: bradafza
        uid: 1002
        comment: "Brad Afzali"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: jiahuazou
        uid: 1003
        comment: "Jiahua Zou"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: sarahsolieman
        uid: 1004
        comment: "Sarah Solieman"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: JerryShi7
        uid: 1005
        comment: "Ji Shi"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: kruing01
        uid: 1006
        comment: "Krutika Ingale"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: kaandgsy
        uid: 1007
        comment: "Kaan Dogusoy"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: bylei
        uid: 1008
        comment: "Brian Lei"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: halmiller
        uid: 1018
        comment: "Haley Miller"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: jennifer
        uid: 1015
        comment: "Jennifer Huang"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: frankchen
        uid: 1016
        comment: "Frank Chen"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: yoonsunghong
        uid: 1012
        comment: "Yoon Sung Hong"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: kwalia
        uid: 1017
        comment: "Kanika Ahluwalia"
        groups: users,admin,docker
        shell: /bin/bash


#    - name: Set authorized key took from url
    - authorized_key:
        user: jhaber
        state: present
        key: https://github.com/jhaber-zz.keys
    - authorized_key:
        user: aculich
        state: present
        key: https://github.com/aculich.keys
    - authorized_key:
        user: bradafza
        state: present
        key: https://github.com/bradafzali.keys
    - authorized_key:
        user: jiahuazou
        state: present
        key: https://github.com/JiahuaZou.keys
    - authorized_key:
        user: yoonsunghong
        state: present
        key: https://github.com/yoonsunghong.keys
    - authorized_key:
        user: sarahsolieman
        state: present
        key: https://github.com/sarahsolieman.keys
    - authorized_key: 
        user: JerryShi7
        state: present
        key: https://github.com/JerryShi7.keys
    - authorized_key:   
        user: kruing01
        state: present
        key: https://github.com/krutikaingale.keys
    - authorized_key:
        user: kaandgsy
        state: present
        key: https://github.com/kaandogusoy.keys
    - authorized_key:
        user: bylei
        state: present
        key: https://github.com/bylei.keys
    - authorized_key:
        user: jennifer
        state: present
        key: https://github.com/Jenniferrrrrr.keys
    - authorized_key:
        user: halmiller
        state: present
        key: https://github.com/halmiller.keys
    - authorized_key:
        user: frankchen
        state: present
    - authorized_key: 
        user: kwalia
        state: present
        key: https://github.com/kwalia1999.keys

    - copy:
        src: charter-school-notebook-server
        dest: /usr/local/bin/charter-school-notebook-server
        owner: root
        group: root
        mode: 0755

    - copy:
        src: kill-charter-school-containers
        dest: /usr/local/sbin/kill-charter-school-containers
        owner: root
        group: root
        mode: 0755

    - copy:
        src: cron-kill-containers
        dest: /etc/cron.d/kill-containers       
        owner: root
        group: root
        mode: 0644

  # This line keeps the procedure from stopping due to users already existing
  ignore_errors: yes
