---
# run this script as: `sudo ansible-playbook jetstream-playbook-mdi.yaml`

- hosts: localhost
  tasks:

    - copy:
        src: jupyter-notebook-server
        dest: /usr/local/bin/jupyter-notebook-server
        owner: root
        group: root
        mode: 0777

  # This line keeps the procedure from stopping due to users already existing
  ignore_errors: yes
