---
# run this script as: `sudo ansible-playbook jetstream-playbook.yaml`
# run this first: `sudo ansible-galaxy install cmprescott.chrome`


- hosts: localhost
  roles:
     - { role: cmprescott.chrome, become: yes }
  tasks:
    # Check if user permissions for passwordless sudo are set up correctly:
    - lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    - lineinfile:
        path: /etc/sudoers.d/90-cloudimg-ubuntu
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    # Remove line (usually at end of file) that would negate passwordless sudo access for all admins
    - lineinfile:
        path: /etc/sudoers
        regexp: '^%users ALL=(ALL) ALL'
        state: absent

    # TO DO: Automatically delete any occurrences of `%users ALL=(ALL) ALL` that occur in /etc/sudoers (use lineinfile for this?)

    # Set up users and groups:
    - user:
        name: jhaber
        uid: 1000
        comment: "Jaren Haber"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: aculich
        uid: 1001
        comment: "Aaron Culich"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: frankwang
        uid: 1028
        comment: "Frank Wang"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: georgewu
        uid: 1029
        comment: "George Wu"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: inderpalkaur
        uid: 1030
        comment: "Inderpal Kaur"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: xueyongliu
        uid: 1031
        comment: "Xueyong Liu"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: kruing01
        uid: 1006
        comment: "Krutika Ingale"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: jennifer
        uid: 1015
        comment: "Jennifer Huang"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: yoonsunghong
        uid: 1012
        comment: "Yoon Sung Hong"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: kwalia
        uid: 1017
        comment: "Kanika Ahluwalia"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: madeleinepeng
        uid: 1024
        comment: "Madeleine Peng"
        groups: users,admin,docker
        shell: /bin/bash        
    - user:
        name: violetyao
        uid: 1026
        comment: "Violet Yao"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: jamesjung
        uid: 1027
        comment: "James Jung"
        groups: users,admin,docker
        shell: /bin/bash

#    - name: Set authorized key took from url
    - authorized_key:
        user: jhaber
        state: present
        key: https://github.com/jhaber-zz.keys
    - authorized_key:
        user: aculich
        state: present
        key: https://github.com/aculich.keys
    - authorized_key:
        user: frankwang
        state: present
        key: https://github.com/fwang084.keys
    - authorized_key:
        user: georgewu
        state: present
        key: https://github.com/wu-george.keys
    - authorized_key:
        user: yoonsunghong
        state: present
        key: https://github.com/yoonsunghong.keys
    - authorized_key:
        user: inderpalkaur
        state: present
        key: https://github.com/ikaur9.keys
    - authorized_key: 
        user: xueyongliu
        state: present
        key: https://github.com/XueYo.keys
    - authorized_key:   
        user: kruing01
        state: present
        key: https://github.com/krutikaingale.keys
    - authorized_key:
        user: jennifer
        state: present
        key: https://github.com/Jenniferrrrrr.keys
    - authorized_key: 
        user: kwalia
        state: present
        key: https://github.com/kwalia1999.keys
    - authorized_key: 
        user: madeleinepeng
        state: present
        key: https://github.com/madeleine-peng.keys
    - authorized_key:
        user: violetyao
        state: present
        key: https://github.com/violetyao.keys
    - authorized_key:
        user: jamesjung
        state: present
        key: https://github.com/jameswsj10.keys

    - copy:
        src: charter-school-notebook-server
        dest: /usr/local/bin/charter-school-notebook-server
        owner: root
        group: root
        mode: 0777

#    - copy:
#        src: kill-charter-school-containers
#        dest: /usr/local/sbin/kill-charter-school-containers
#        owner: root
#        group: root
#        mode: 0755

#    - copy:
#        src: cron-kill-containers
#        dest: /etc/cron.d/kill-containers       
#        owner: root
#        group: root
#        mode: 0644

  # This line keeps the procedure from stopping due to users already existing
  ignore_errors: yes
