---
# run this script as: `sudo ansible-playbook jetstream-playbook.yaml`
# run this first: `sudo ansible-galaxy install cmprescott.chrome`


- hosts: localhost
  roles:
     - { role: cmprescott.chrome, become: yes }
  tasks:
    # Check if user permissions for passwordless sudo are set up correctly:
    - lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    - lineinfile:
        path: /etc/sudoers.d/90-cloudimg-ubuntu
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    # Remove line (usually at end of file) that would negate passwordless sudo access for all admins
    - lineinfile:
        path: /etc/sudoers
        regexp: '^%users ALL=(ALL) ALL'
        state: absent

    # TO DO: Automatically delete any occurrences of `%users ALL=(ALL) ALL` that occur in /etc/sudoers (use lineinfile for this?)

    # Set up users and groups:
    - user:
        name: jhaber
        uid: 1000
        comment: "Jaren Haber"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: aculich
        uid: 1001
        comment: "Aaron Culich"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: yoonsunghong
        uid: 1002
        comment: "Yoon Sung Hong"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: artemtkachuk
        uid: 1008
        comment: "Artem Tkachuk"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: yingliu
        uid: 1011
        comment: "Ying Liu"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: devbali
        uid: 1014
        comment: "Dev Bali"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: robertalward
        uid: 1016
        comment: "Robert Alward"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: hwarner
        uid: 1017
        comment: "Hannah Warner"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: miclin
        uid: 1018
        comment: "Michael Lin"
        groups: users,admin,docker
        shell: /bin/bash

#    - name: Set authorized key took from url
    - authorized_key:
        user: jhaber
        state: present
        key: https://github.com/jhaber-zz.keys
    - authorized_key:
        user: aculich
        state: present
        key: https://github.com/aculich.keys
    - authorized_key:
        user: yoonsunghong
        state: present
        key: https://github.com/yoonsunghong.keys
    - authorized_key:
        user: artemtkachuk
        state: present
        key: https://github.com/artem-tkachuk.keys
    - authorized_key:
       user: yingliu
       state: present
       key: https://github.com/yingliu1206.keys
    - authorized_key:
       user: devbali
       state: present
       key: https://github.com/devbali.keys
    - authorized_key:
       user: robertalward
       state: present
       key: https://github.com/ThaiHipster.keys
    - authorized_key:
       user: hwarner
       state: present
       key: https://github.com/hwarnuh.keys
    - authorized_key:
       user: miclin
       state: present
       key: https://github.com/Miclin2014.keys

    - copy:
        src: charter-school-notebook-server
        dest: /usr/local/bin/charter-school-notebook-server
        owner: root
        group: root
        mode: 0777

    - copy:
        src: kill-charter-school-containers
        dest: /usr/local/sbin/kill-charter-school-containers
        owner: root
        group: root
        mode: 0755

  #  The following code will automatically kill all docker containers every night at 3 or 4 am.
  #  Un-comment then run this script to activate this functionality.
  #
  # - copy:
  #    src: cron-kill-containers
  #    dest: /etc/cron.d/kill-containers       
  #    owner: root
  #    group: root
  #    mode: 0644

  # This line keeps the procedure from stopping due to users already existing
  ignore_errors: yes
