---
# INSTRUCTIONS FOR CREATING JUPYTER NOTEBOOK SERVER ON MDI SERVER:
#
# 0. On server, update line 2 in the `jupyter notebook server` script (in this same directory) with your own netid, as in:
# VOL=/home/jh2260 --> VOL=/home/YOUR_NETID
#
# 1. On server, run this script as: `sudo ansible-playbook jetstream-playbook-mdi.yaml`
#
# 2. On server, call `jupyter-notebook-server` (now a recognized command). 
# This should display a long URL; copy down the token, which is everything after `?token=...`
# You will need the token when logging into the server (see step 4).
# If it doesn't display this, find your containers number by executing: `sudo docker ps`,
# then have it show its info (ending with the token) by executing:
# `sudo docker exec DOCKER_NUM jupyter notebook list`
#
# 3. On local machine, execute the following:
# sudo ssh -i ~/.ssh/id_rsa -N -f -L localhost:8888:localhost:8888 jh2260@jade.mdi.georgetown.edu -p 8800
# (you may need to change the netid or path to ssh key)
#
# 4. In web browser, access jupyter notebook server by going to:
# localhost:8888
# Use the token to validate (see step 2). 


- hosts: localhost
  tasks:

    - copy:
        src: ../notebook_servers/jupyter-notebook-server
        dest: /usr/local/bin/jupyter-notebook-server
        owner: root
        group: root
        mode: 0777
